{
 "title": "K6 Monitoring, Troubleshooting and Reporting - Protocol and Browser",
 "description": "Dashboard for Grafana K6 load test monitoring, troubleshooting and reporting. As concise and minimal as possible, whilst including critical data points. It includes metrics for both Protocol (http_...) and Browser (browser_...) tests. It includes Groups (Transactions) for protocol level testing.",
 "tags": [
  "k6",
  "load testing"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Transaction",
    "query": {
     "query": "show tag values with key = \"group\" where $timeFilter"
    }
   },
   {
    "name": "URL",
    "label": "URL",
    "query": {
     "query": "SHOW TAG VALUES WITH KEY = \"name\" WHERE $timeFilter and \"group\" =~ /^$Transaction$/"
    }
   },
   {
    "name": "PageURL",
    "label": "Page URL",
    "query": {
     "query": "\tSELECT \"url\" from \"browser_web_vital_fcp\" WHERE $timeFilter"
    }
   }
  ]
 },
 "panels": [
  { "title": "Test Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Active VUs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Active VUs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Request Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "query": "SELECT sum(\"value\") FROM \"http_reqs\" WHERE $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_failed",
     "query": "SELECT sum(\"value\") FROM \"http_req_failed\" WHERE (\"group\"::tag =~ /^$Group$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Error%",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_sent",
     "query": "SELECT sum(\"value\") FROM \"http_write_request_bytes\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Bytes Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_received",
     "query": "SELECT sum(\"value\") FROM \"http_write_request_bytes\" WHERE $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Threads (Virtual Users)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Active VUs",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vus",
     "query": "SELECT \"value\" FROM \"vus\" WHERE $timeFilter GROUP BY time(1s) fill(null)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput (Requests per Second)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Requests per Second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors Per Second",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Num Errors",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_req_failed",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Passed vs Failed Checks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Passed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "checks",
     "query": "SELECT count(\"value\") FROM \"checks\" WHERE \"value\" = 1 AND $timeFilter GROUP BY time($__interval) fill(none)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "Failed",
     "query": "SELECT count(\"value\") FROM \"checks\" WHERE \"value\" = 0 AND $timeFilter GROUP BY time($__interval) fill(none)"
    }
   ]
  },
  { "title": "Core Web Vitals Overview", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 } },
  {
   "title": "LCP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "LCP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "browser_web_vital_lcp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "INP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "INP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "browser_web_vital_inp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CLS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CLS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "browser_web_vital_cls",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FCP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "FCP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "browser_web_vital_fcp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TTFB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "TTFP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "browser_web_vital_ttfb",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "FID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "browser_web_vital_fid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "HTTP Requests Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Response Time Variance",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "SELECT min(\"value\") as \"Min\", mean(\"value\")-min(\"value\") as \"Avg\", percentile(\"value\", 95)-mean(\"value\") as \"p95\", max(\"value\")- percentile(\"value\", 95) as \"Max\" FROM \"http_req_duration\" WHERE $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Time Distribution",
   "type": "barchart",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Sending",
     "measurement": "http_req_sending",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Waiting",
     "measurement": "http_req_waiting",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Receiving",
     "measurement": "http_req_receiving",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Times Distribution Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "p95",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    },
    {
     "alias": "avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Time Breakdown Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Sending",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_sending",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Waiting",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_waiting",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Receiving",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_receiving",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transactions Overall (can filter by transaction)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time Variance",
     "type": "barchart",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "query": "SELECT min(\"value\") as \"Min\", mean(\"value\")-min(\"value\") as \"Avg\", percentile(\"value\", 95)-mean(\"value\") as \"p95\", max(\"value\")- percentile(\"value\", 95) as \"Max\" FROM \"group_duration\" WHERE $timeFilter AND \"group\" =~/^$Transaction$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Transaction Response Times Over Time",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "group::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "group_duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "=~", "value": "/^$Transaction$/" }
       ]
      }
     ]
    },
    {
     "title": "Response Times Distribution Over Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 107 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "group_duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "=~", "value": "/^$Transaction$/" }
       ]
      },
      {
       "alias": "p95",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "group_duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "=~", "value": "/^$Transaction$/" }
       ]
      },
      {
       "alias": "avg",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "group_duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "=~", "value": "/^$Transaction$/" }
       ]
      },
      {
       "alias": "min",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "group_duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "=~", "value": "/^$Transaction$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Request (can filter by transaction and url)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time Variance",
     "type": "barchart",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "query": "SELECT min(\"value\") as \"Min\", mean(\"value\")-min(\"value\") as \"Avg\", percentile(\"value\", 95)-mean(\"value\") as \"p95\", max(\"value\")- percentile(\"value\", 95) as \"Max\" FROM \"http_req_duration\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Request Time Distribution",
     "type": "barchart",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 119 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "Sending",
       "measurement": "http_req_sending",
       "query": "SELECT mean(\"value\") FROM \"http_req_sending\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Waiting",
       "measurement": "http_req_waiting",
       "query": "SELECT mean(\"value\") FROM \"http_req_waiting\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Receiving",
       "measurement": "http_req_receiving",
       "query": "SELECT mean(\"value\") FROM \"http_req_receiving\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Response Times Over Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "query": "SELECT max(\"value\") FROM \"http_req_duration\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/ GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      },
      {
       "alias": "p95",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "query": "SELECT percentile(\"value\", 95) FROM \"http_req_duration\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/ GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "alias": "avg",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "query": "SELECT mean(\"value\") FROM \"http_req_duration\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/ GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "min",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "query": "SELECT min(\"value\") FROM \"http_req_duration\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/ GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Request Time Breakdown Over Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 123 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "Total",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "query": "SELECT mean(\"value\") FROM \"http_req_duration\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/ GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Sending",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_sending",
       "query": "SELECT mean(\"value\") FROM \"http_req_sending\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/ GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Waiting",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_waiting",
       "query": "SELECT mean(\"value\") FROM \"http_req_waiting\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/ GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Receiving",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_receiving",
       "query": "SELECT mean(\"value\") FROM \"http_req_receiving\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/ GROUP BY time($__interval) fill(null)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Core Web Vitals (can filter by page URL)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "LCP",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "LCP",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "browser_web_vital_lcp",
       "query": "SELECT mean(\"value\") FROM \"browser_web_vital_lcp\" WHERE (\"name\"::tag =~ /^$PageURL/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "name::tag", "operator": "=~", "value": "/^$PageURL$/" }
       ]
      }
     ]
    },
    {
     "title": "INP",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "INP",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "browser_web_vital_inp",
       "query": "SELECT mean(\"value\") FROM \"browser_web_vital_inp\" WHERE (\"name\"::tag =~ /^$PageURL/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CLS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "CLS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "browser_web_vital_cls",
       "query": "SELECT mean(\"value\") FROM \"browser_web_vital_cls\" WHERE (\"name\"::tag =~ /^$PageURL/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FCP",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "FCP",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "browser_web_vital_fcp",
       "query": "SELECT mean(\"value\") FROM \"browser_web_vital_fcp\" WHERE (\"name\"::tag =~ /^$PageURL/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "TTFB",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "TTFP",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "browser_web_vital_ttfb",
       "query": "SELECT mean(\"value\") FROM \"browser_web_vital_ttfb\" WHERE (\"name\"::tag =~ /^$PageURL/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FID",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 70 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "FID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "browser_web_vital_fid",
       "query": "SELECT mean(\"value\") FROM \"browser_web_vital_fid\" WHERE (\"name\"::tag =~ /^$PageURL/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Core Web Vitals by Page URL",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 77 },
     "targets": [
      {
       "alias": "CLS",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT mean(\"value\") as \"CLS\" FROM browser_web_vital_cls WHERE $timeFilter  and \"name\" =~ /^$PageURL/ group by \"name\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "alias": "FCP",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT mean(\"value\") as \"FCP\" FROM browser_web_vital_fcp WHERE $timeFilter  and \"name\" =~ /^$PageURL/ group by \"name\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "alias": "FID",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT mean(\"value\") as \"FID\" FROM browser_web_vital_fid WHERE $timeFilter  and \"name\" =~ /^$PageURL/ group by \"name\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "alias": "INP",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT mean(\"value\") as \"INP\" FROM browser_web_vital_inp WHERE $timeFilter  and \"name\" =~ /^$PageURL/ group by \"name\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "alias": "LCP",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT mean(\"value\") as \"LCP\" FROM browser_web_vital_lcp WHERE $timeFilter  and \"name\" =~ /^$PageURL/ group by \"name\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "alias": "TTFP",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT mean(\"value\") as \"TTFB\" FROM browser_web_vital_ttfb WHERE $timeFilter  and \"name\" =~ /^$PageURL/ group by \"name\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Response Times Tables (can filter by transaction and url)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions Aggregate (can filter by transaction)",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 36 },
     "targets": [
      {
       "alias": "aggregate",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT count(\"value\") as \"Count\", min(\"value\") as \"Min\", mean(\"value\") as \"Avg\", percentile(\"value\", 95) as \"p95\", max(\"value\") as \"Max\" FROM group_duration WHERE $timeFilter and (\"group\"::tag =~ /^$Transaction$/) GROUP BY \"group\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Requests Response Times (can filter by transction and url)",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 77 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT count(\"value\") as \"Count\", min(\"value\") as \"Min\", mean(\"value\") as \"Avg\", max(\"value\") as \"Max\", percentile(\"value\", 95) as \"p95\" FROM http_req_duration WHERE $timeFilter AND (\"group\"::tag =~ /^$Transaction$/) AND (\"name\" =~ /^$URL$/) GROUP BY \"group\", \"name\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Errors and Checks (can filter by transaction and url)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 }
  },
  {
   "title": "HTTP Request Errors (can filter by transaction and url)",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 37 },
   "targets": [
    {
     "query": "SELECT \"group\", \"method\", \"name\", \"status\", \"error_code\", \"value\" FROM \"http_req_failed\" WHERE $timeFilter AND error_code != '' AND \"group\" =~ /^$Transaction$/ AND \"name\" =~ /^$URL$/ "
    }
   ]
  },
  {
   "title": "Failed Checks (can filter by transaction)",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 51 },
   "targets": [
    {
     "query": "SELECT \"value\" FROM \"checks\" WHERE $timeFilter AND \"group\" =~ /^$Transaction$/ AND \"value\" = 0 GROUP BY \"check\", \"group\""
    }
   ]
  }
 ]
}