{
 "title": "K6 Monitoring, Troubleshooting and Reporting - Protocol and Browser",
 "description": "Dashboard for Grafana K6 load test monitoring, troubleshooting and reporting. As concise and minimal as possible, whilst including critical data points. It includes metrics for both Protocol (http_...) and Browser (browser_...) tests. It includes Groups (Transactions) for protocol level testing.",
 "tags": [
  "k6",
  "load testing"
 ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "Transaction",
    "query": {
     "query": "//show tag values with key = \"group\" where $timeFilter\r\n\r\n//import \"strings\"\r\n\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => exists r.group)\r\n  |> keep(columns: [\"group\"])\r\n  |> distinct(column: \"group\")\r\n  //|> map(fn: (r) => ({ r with _value: strings.trimPrefix(v: r._value, prefix: \"::\") }))\r\n"
    }
   },
   {
    "name": "URL",
    "label": "URL",
    "query": {
     "query": "//SHOW TAG VALUES WITH KEY = \"name\" WHERE $timeFilter and \"group\" =~ /^$Transaction$/\r\n\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r.group =~ /^${Transaction}$/ and\r\n    exists r[\"name\"]\r\n  )\r\n  |> keep(columns: [\"name\"])\r\n  |> distinct(column: \"name\")\r\n"
    }
   },
   {
    "name": "PageURL",
    "label": "Page URL",
    "query": {
     "query": "\tSELECT \"url\" from \"browser_web_vital_fcp\" WHERE $timeFilter"
    }
   }
  ]
 },
 "panels": [
  { "title": "Test Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Current Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Active VUs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Max Threads",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "alias": "Active VUs",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vus",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Current Request Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "query": "//SELECT sum(\"value\") FROM \"http_reqs\" WHERE $timeFilter GROUP BY time(1s) fill(null)\r\n\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_reqs\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(\r\n    every: 1s,\r\n    fn: sum,\r\n    createEmpty: true\r\n  )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Requests",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_reqs\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> keep(columns: [\"_value\"])\r\n  |> count()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Errors",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_failed",
     "query": "// SELECT sum(\"value\") FROM \"http_req_failed\" WHERE (\"group\"::tag =~ /^$Group$/) AND $timeFilter GROUP BY time($__interval) fill(null)\r\n\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_req_failed\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(\r\n    every: $__interval,\r\n    fn: sum,\r\n    createEmpty: true\r\n  )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Error%",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "alias": "success",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "query": "//SELECT sum(\"value\") FROM \"http_reqs\" WHERE $timeFilter\r\n\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_reqs\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> keep(columns: [\"_value\"])\r\n  |> sum()",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    },
    { "expression": "$B/$A", "type": "math" }
   ]
  },
  {
   "title": "Total Bytes Sent",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_sent",
     "query": "// SELECT sum(\"value\") FROM \"http_write_request_bytes\" WHERE $timeFilter GROUP BY time($__interval) fill(null)\r\n\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_write_response_bytes\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(\r\n    every: $__interval,\r\n    fn: sum,\r\n    createEmpty: true\r\n  )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Total Bytes Received",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "data_received",
     "query": "//SELECT sum(\"value\") FROM \"http_write_request_bytes\" WHERE $timeFilter GROUP BY time($__interval) fill(null)\r\n\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_write_request_bytes\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(\r\n    every: $__interval,\r\n    fn: sum,\r\n    createEmpty: true\r\n  )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Active Threads (Virtual Users)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Active VUs",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vus",
     "query": "// SELECT \"value\" FROM \"vus\" WHERE $timeFilter GROUP BY time(1s) fill(null)\r\n\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"vus\" and r._field == \"value\")",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Throughput (Requests per Second)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Requests per Second",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_reqs\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(\r\n    every: 1s,\r\n    fn: sum,\r\n    createEmpty: true\r\n  )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Errors Per Second",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "Num Errors",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_req_failed",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_req_failed\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> aggregateWindow(\r\n    every: 1s,\r\n    fn: sum,\r\n    createEmpty: true\r\n  )",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Passed vs Failed Checks",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "Passed",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "checks",
     "query": "//SELECT count(\"value\") FROM \"checks\" WHERE \"value\" = 1 AND $timeFilter GROUP BY time($__interval) fill(none)\r\n\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"checks\" and\r\n    r._field == \"value\" and\r\n    r._value == 1\r\n  )\r\n  |> aggregateWindow(\r\n    every: $__interval,\r\n    fn: count,\r\n    createEmpty: false\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> rename(columns: {\"_value\": \"Passed\"})",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "value::field", "operator": "=", "value": "0" }
     ]
    },
    {
     "alias": "Failed",
     "query": "//SELECT count(\"value\") FROM \"checks\" WHERE \"value\" = 0 AND $timeFilter GROUP BY time($__interval) fill(none)\r\n\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"checks\" and\r\n    r._field == \"value\" and\r\n    r._value == 0\r\n  )  \r\n  |> aggregateWindow(\r\n    every: $__interval,\r\n    fn: count,\r\n    createEmpty: false\r\n  )\r\n  |> keep(columns: [\"_time\", \"_value\"])\r\n  |> rename(columns: {\"_value\": \"Failed\"})"
    }
   ]
  },
  { "title": "Core Web Vitals Overview", "type": "text", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "LCP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "LCP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "browser_web_vital_lcp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "INP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "INP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "browser_web_vital_inp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "CLS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "CLS",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "browser_web_vital_cls",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FCP",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "FCP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "browser_web_vital_fcp",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "TTFB",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "TTFP",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "browser_web_vital_ttfb",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "FID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "FID",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "browser_web_vital_fid",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "HTTP Requests Overall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Response Time Variance",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "//SELECT min(\"value\") as \"Min\", mean(\"value\")-min(\"value\") as \"Avg\", percentile(\"value\", 95)-mean(\"value\") as \"p95\", max(\"value\")- percentile(\"value\", 95) as \"Max\" FROM \"http_req_duration\" WHERE $timeFilter\r\n\r\n// 1. MIN\r\nminVal = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> group()\r\n  |> min()\r\n  |> map(fn: (r) => ({ _time: v.timeRangeStop, Min: r._value }))\r\n\r\n// 2. MEAN\r\nmeanVal = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> group()\r\n  |> mean()\r\n  |> map(fn: (r) => ({ _time: v.timeRangeStop, Mean: r._value }))\r\n\r\n// 3. P95\r\np95Val = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> group()\r\n  |> quantile(q: 0.95, method: \"estimate_tdigest\")\r\n  |> map(fn: (r) => ({ _time: v.timeRangeStop, P95: r._value }))\r\n\r\n// 4. MAX\r\nmaxVal = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> group()\r\n  |> max()\r\n  |> map(fn: (r) => ({ _time: v.timeRangeStop, Max: r._value }))\r\n\r\n// Step 1: Join min + mean\r\nminMean = join(tables: {min: minVal, mean: meanVal}, on: [\"_time\"])\r\n\r\n// Step 2: Join result with p95\r\nminMeanP95 = join(tables: {left: minMean, right: p95Val}, on: [\"_time\"])\r\n\r\n// Step 3: Join result with max\r\nallStats = join(tables: {left: minMeanP95, right: maxVal}, on: [\"_time\"])\r\n\r\n// Final mapping\r\nallStats\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    \"1_Min\": r.Min,\r\n    \"2_Avg\": r.Mean - r.Min,\r\n    \"3_p95\": r.P95 - r.Mean,\r\n    \"4_Max\": r.Max - r.P95\r\n  }))\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Time Distribution",
   "type": "barchart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Sending",
     "measurement": "http_req_sending",
     "query": "from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_req_duration\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> group()\r\n  |> histogram(\r\n    column: \"_value\",\r\n    upperBoundColumn: \"le\",\r\n    countColumn: \"count\",\r\n    bins: [3.0, 4.0, 10.0, 20.0, 40.0, 80.0, 160.0, 10000.0]\r\n  )\r\n  |> keep(columns: [\"le\", \"count\"])\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Waiting",
     "measurement": "http_req_waiting",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Receiving",
     "measurement": "http_req_receiving",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Response Times Distribution Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "max",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "minValues = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> aggregateWindow(every: $__interval, fn: min, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"A Min\" }))\r\n\r\nmeanValues = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"B Mean\" }))\r\n\r\np95Values = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> aggregateWindow(column: \"_value\", every: $__interval, fn: (column, tables=<-) => tables |> quantile(q: 0.95, column: column, method: \"estimate_tdigest\"), createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"C P95\" }))\r\n\r\nmaxValues = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> aggregateWindow(every: $__interval, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"D Max\" }))\r\n\r\nunion(tables: [minValues, meanValues,p95Values, maxValues])\r\n  |> group(columns: [\"phase\"])\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"Response Breakdown\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ]
    },
    {
     "alias": "p95",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    },
    {
     "alias": "avg",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "min",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Request Time Breakdown Over Time",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "alias": "Total",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "query": "sending = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_sending\" and r._field == \"value\")\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"Request Sending\" }))\r\n\r\nwaiting = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_waiting\" and r._field == \"value\")\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"Request Waiting\" }))\r\n\r\nreceiving = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_receiving\" and r._field == \"value\")\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"Request Receiving\" }))\r\n\r\nduration = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"Total Duration\" }))\r\n\r\nunion(tables: [sending, waiting, receiving, duration])\r\n  |> group(columns: [\"phase\"])\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"Request Breakdown + Total\")\r\n",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Sending",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_sending",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Waiting",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_waiting",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Receiving",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "http_req_receiving",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Transactions Overall (can filter by transaction)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 41 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time Variance",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "query": "//SELECT min(\"value\") as \"Min\", mean(\"value\")-min(\"value\") as \"Avg\", percentile(\"value\", 95)-mean(\"value\") as \"p95\", max(\"value\")- percentile(\"value\", 95) as \"Max\" FROM \"group_duration\" WHERE $timeFilter AND \"group\" =~/^$Transaction$/\r\n\r\n// 1. MIN\r\nminVal = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> group()\r\n  |> min()\r\n  |> map(fn: (r) => ({ _time: v.timeRangeStop, Min: r._value }))\r\n\r\n// 2. MEAN\r\nmeanVal = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> group()\r\n  |> mean()\r\n  |> map(fn: (r) => ({ _time: v.timeRangeStop, Mean: r._value }))\r\n\r\n// 3. P95\r\np95Val = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> group()\r\n  |> quantile(q: 0.95, method: \"estimate_tdigest\")\r\n  |> map(fn: (r) => ({ _time: v.timeRangeStop, P95: r._value }))\r\n\r\n// 4. MAX\r\nmaxVal = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> group()\r\n  |> max()\r\n  |> map(fn: (r) => ({ _time: v.timeRangeStop, Max: r._value }))\r\n\r\n// Step 1: Join min + mean\r\nminMean = join(tables: {min: minVal, mean: meanVal}, on: [\"_time\"])\r\n\r\n// Step 2: Join result with p95\r\nminMeanP95 = join(tables: {left: minMean, right: p95Val}, on: [\"_time\"])\r\n\r\n// Step 3: Join result with max\r\nallStats = join(tables: {left: minMeanP95, right: maxVal}, on: [\"_time\"])\r\n\r\n// Final mapping\r\nallStats\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    Min: r.Min,\r\n    Avg: r.Mean - r.Min,\r\n    p95: r.P95 - r.Mean,\r\n    Max: r.Max - r.P95\r\n  }))\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Transaction Response Times Over Time",
     "type": "timeseries",
     "gridPos": { "h": 15, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "group::tag" ], "type": "tag" },
        { "params": [ "0" ], "type": "fill" }
       ],
       "measurement": "group_duration",
       "query": "minValues = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"group_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> aggregateWindow(every: $__interval, fn: min, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"A Min\" }))\r\n\r\nmeanValues = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"group_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"B Mean\" }))\r\n\r\np95Values = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"group_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> aggregateWindow(column: \"_value\", every: $__interval, fn: (column, tables=<-) => tables |> quantile(q: 0.95, column: column, method: \"estimate_tdigest\"), createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"C P95\" }))\r\n\r\nmaxValues = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"group_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> aggregateWindow(every: $__interval, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"D Max\" }))\r\n\r\nunion(tables: [minValues, meanValues, p95Values, maxValues])\r\n  |> group(columns: [\"phase\"])\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"Response Breakdown\")\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "=~", "value": "/^$Transaction$/" }
       ]
      }
     ]
    },
    {
     "title": "Response Times Distribution Over Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 103 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "group_duration",
       "query": "minValues = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> aggregateWindow(every: $__interval, fn: min, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"A Min\" }))\r\n\r\nmeanValues = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"B Mean\" }))\r\n\r\np95Values = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> aggregateWindow(column: \"_value\", every: $__interval, fn: (column, tables=<-) => tables |> quantile(q: 0.95, column: column, method: \"estimate_tdigest\"), createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"C P95\" }))\r\n\r\nmaxValues = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> aggregateWindow(every: $__interval, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"D Max\" }))\r\n\r\nunion(tables: [minValues, meanValues, p95Values, maxValues])\r\n  |> group(columns: [\"phase\"])\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"Response Breakdown\")\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "=~", "value": "/^$Transaction$/" }
       ]
      },
      {
       "alias": "p95",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "group_duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "=~", "value": "/^$Transaction$/" }
       ]
      },
      {
       "alias": "avg",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "group_duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "=~", "value": "/^$Transaction$/" }
       ]
      },
      {
       "alias": "min",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "group_duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ],
       "tags": [
        { "key": "group::tag", "operator": "=~", "value": "/^$Transaction$/" }
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "HTTP Request (can filter by transaction and url)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 },
   "collapsed": true,
   "panels": [
    {
     "title": "Response Time Variance",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "query": "//SELECT min(\"value\") as \"Min\", mean(\"value\")-min(\"value\") as \"Avg\", percentile(\"value\", 95)-mean(\"value\") as \"p95\", max(\"value\")- percentile(\"value\", 95) as \"Max\" FROM \"http_req_duration\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/\r\n\r\n// 1. MIN\r\nminVal = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> filter(fn: (r) => contains(value: r.name, set: ${URL:json}))\r\n  |> group()\r\n  |> min()\r\n  |> map(fn: (r) => ({ _time: v.timeRangeStop, Min: r._value }))\r\n\r\n// 2. MEAN\r\nmeanVal = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> filter(fn: (r) => contains(value: r.name, set: ${URL:json}))\r\n  |> group()\r\n  |> mean()\r\n  |> map(fn: (r) => ({ _time: v.timeRangeStop, Mean: r._value }))\r\n\r\n// 3. P95\r\np95Val = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> filter(fn: (r) => contains(value: r.name, set: ${URL:json}))\r\n  |> group()\r\n  |> quantile(q: 0.95, method: \"estimate_tdigest\")\r\n  |> map(fn: (r) => ({ _time: v.timeRangeStop, P95: r._value }))\r\n\r\n// 4. MAX\r\nmaxVal = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> filter(fn: (r) => contains(value: r.name, set: ${URL:json}))\r\n  |> group()\r\n  |> max()\r\n  |> map(fn: (r) => ({ _time: v.timeRangeStop, Max: r._value }))\r\n\r\n// Step 1: Join min + mean\r\nminMean = join(tables: {min: minVal, mean: meanVal}, on: [\"_time\"])\r\n\r\n// Step 2: Join result with p95\r\nminMeanP95 = join(tables: {left: minMean, right: p95Val}, on: [\"_time\"])\r\n\r\n// Step 3: Join result with max\r\nallStats = join(tables: {left: minMeanP95, right: maxVal}, on: [\"_time\"])\r\n\r\n// Final mapping\r\nallStats\r\n  |> map(fn: (r) => ({\r\n    _time: r._time,\r\n    \"1_Min\": r.Min,\r\n    \"2_Avg\": r.Mean - r.Min,\r\n    \"3_p95\": r.P95 - r.Mean,\r\n    \"4_Max\": r.Max - r.P95\r\n  }))\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Request Time Distribution",
     "type": "barchart",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 181 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "Sending",
       "measurement": "http_req_sending",
       "query": "//SELECT mean(\"value\") FROM \"http_req_sending\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/\r\n//SELECT mean(\"value\") FROM \"http_req_waiting\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/\r\n//SELECT mean(\"value\") FROM \"http_req_receiving\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/\r\n\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_req_duration\" and\r\n    r._field == \"value\"\r\n  )\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> filter(fn: (r) => contains(value: r.name, set: ${URL:json}))\r\n  |> group()\r\n  |> histogram(\r\n    column: \"_value\",\r\n    upperBoundColumn: \"le\",\r\n    countColumn: \"count\",\r\n    bins: [3.0, 4.0, 10.0, 20.0, 40.0, 80.0, 160.0, 10000.0]\r\n  )\r\n  |> keep(columns: [\"le\", \"count\"])\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Waiting",
       "measurement": "http_req_waiting",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Receiving",
       "measurement": "http_req_receiving",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Response Times Distribution Over Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 192 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "max",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "query": "//SELECT max(\"value\") FROM \"http_req_duration\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/ GROUP BY time($__interval) fill(null)\r\n//SELECT percentile(\"value\", 95) FROM \"http_req_duration\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/ GROUP BY time($__interval) fill(null)\r\n//SELECT mean(\"value\") FROM \"http_req_duration\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/ GROUP BY time($__interval) fill(null)\r\n//SELECT min(\"value\") FROM \"http_req_duration\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/ GROUP BY time($__interval) fill(null)\r\n\r\nminValues = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> filter(fn: (r) => contains(value: r.name, set: ${URL:json}))\r\n  |> aggregateWindow(every: $__interval, fn: min, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"A Min\" }))\r\n\r\nmeanValues = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> filter(fn: (r) => contains(value: r.name, set: ${URL:json}))\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"B Mean\" }))\r\n\r\np95Values = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> filter(fn: (r) => contains(value: r.name, set: ${URL:json}))\r\n  |> aggregateWindow(column: \"_value\", every: $__interval, fn: (column, tables=<-) => tables |> quantile(q: 0.95, column: column, method: \"estimate_tdigest\"), createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"B P95\" }))\r\n\r\nmaxValues = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> filter(fn: (r) => contains(value: r.name, set: ${URL:json}))\r\n  |> aggregateWindow(every: $__interval, fn: max, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"D Max\" }))\r\n\r\nunion(tables: [minValues, meanValues, p95Values, maxValues])\r\n  |> group(columns: [\"phase\"])\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"Response Breakdown\")\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ]
       ]
      },
      {
       "alias": "p95",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "alias": "avg",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "min",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Request Time Breakdown Over Time",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 192 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "Total",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "http_req_duration",
       "query": "//SELECT mean(\"value\") FROM \"http_req_duration\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/ GROUP BY time($__interval) fill(none)\r\n//SELECT mean(\"value\") FROM \"http_req_sending\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/ GROUP BY time($__interval) fill(null)\r\n//SELECT mean(\"value\") FROM \"http_req_waiting\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/ GROUP BY time($__interval) fill(null)\r\n//SELECT mean(\"value\") FROM \"http_req_receiving\" WHERE $timeFilter and \"group\" =~/^$Transaction$/ and \"name\" =~/^$URL$/ GROUP BY time($__interval) fill(null)\r\n\r\nsending = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_sending\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> filter(fn: (r) => contains(value: r.name, set: ${URL:json}))\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"Request Sending\" }))\r\n\r\nwaiting = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_waiting\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> filter(fn: (r) => contains(value: r.name, set: ${URL:json}))\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"Request Waiting\" }))\r\n\r\nreceiving = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_receiving\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> filter(fn: (r) => contains(value: r.name, set: ${URL:json}))\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"Request Receiving\" }))\r\n\r\nduration = from(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) => r._measurement == \"http_req_duration\" and r._field == \"value\")\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> filter(fn: (r) => contains(value: r.name, set: ${URL:json}))\r\n  |> aggregateWindow(every: $__interval, fn: mean, createEmpty: false)\r\n  |> map(fn: (r) => ({ r with phase: \"Total Duration\" }))\r\n\r\nunion(tables: [sending, waiting, receiving, duration])\r\n  |> group(columns: [\"phase\"])\r\n  |> drop(columns: [\"_start\", \"_stop\"])\r\n  |> yield(name: \"Request Breakdown + Total\")\r\n",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Sending",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_sending",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Waiting",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_waiting",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      },
      {
       "alias": "Receiving",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "http_req_receiving",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Core Web Vitals (can filter by page URL)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 },
   "collapsed": true,
   "panels": [
    {
     "title": "LCP",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 449 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "LCP",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "browser_web_vital_lcp",
       "query": "SELECT mean(\"value\") FROM \"browser_web_vital_lcp\" WHERE (\"name\"::tag =~ /^$PageURL/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "name::tag", "operator": "=~", "value": "/^$PageURL$/" }
       ]
      }
     ]
    },
    {
     "title": "INP",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 449 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "INP",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "browser_web_vital_inp",
       "query": "SELECT mean(\"value\") FROM \"browser_web_vital_inp\" WHERE (\"name\"::tag =~ /^$PageURL/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "CLS",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 449 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "CLS",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "browser_web_vital_cls",
       "query": "SELECT mean(\"value\") FROM \"browser_web_vital_cls\" WHERE (\"name\"::tag =~ /^$PageURL/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FCP",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 456 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "FCP",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "browser_web_vital_fcp",
       "query": "SELECT mean(\"value\") FROM \"browser_web_vital_fcp\" WHERE (\"name\"::tag =~ /^$PageURL/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "TTFB",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 456 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "TTFP",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "browser_web_vital_ttfb",
       "query": "SELECT mean(\"value\") FROM \"browser_web_vital_ttfb\" WHERE (\"name\"::tag =~ /^$PageURL/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "FID",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 456 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "alias": "FID",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "none" ], "type": "fill" }
       ],
       "measurement": "browser_web_vital_fid",
       "query": "SELECT mean(\"value\") FROM \"browser_web_vital_fid\" WHERE (\"name\"::tag =~ /^$PageURL/) AND $timeFilter GROUP BY time($__interval) fill(none)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Core Web Vitals by Page URL",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 463 },
     "targets": [
      {
       "alias": "CLS",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT mean(\"value\") as \"CLS\" FROM browser_web_vital_cls WHERE $timeFilter  and \"name\" =~ /^$PageURL/ group by \"name\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "alias": "FCP",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT mean(\"value\") as \"FCP\" FROM browser_web_vital_fcp WHERE $timeFilter  and \"name\" =~ /^$PageURL/ group by \"name\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "alias": "FID",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT mean(\"value\") as \"FID\" FROM browser_web_vital_fid WHERE $timeFilter  and \"name\" =~ /^$PageURL/ group by \"name\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "alias": "INP",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT mean(\"value\") as \"INP\" FROM browser_web_vital_inp WHERE $timeFilter  and \"name\" =~ /^$PageURL/ group by \"name\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "alias": "LCP",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT mean(\"value\") as \"LCP\" FROM browser_web_vital_lcp WHERE $timeFilter  and \"name\" =~ /^$PageURL/ group by \"name\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      },
      {
       "alias": "TTFP",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT mean(\"value\") as \"TTFB\" FROM browser_web_vital_ttfb WHERE $timeFilter  and \"name\" =~ /^$PageURL/ group by \"name\" fill(0)",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Response Times Tables (can filter by transaction and url)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 44 },
   "collapsed": true,
   "panels": [
    {
     "title": "Transactions Aggregate (can filter by transaction)",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 531 },
     "targets": [
      {
       "alias": "aggregate",
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT count(\"value\") as \"Count\", min(\"value\") as \"Min\", mean(\"value\") as \"Avg\", percentile(\"value\", 95) as \"p95\", max(\"value\") as \"Max\" FROM group_duration WHERE $timeFilter and (\"group\"::tag =~ /^$Transaction$/) GROUP BY \"group\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      }
     ]
    },
    {
     "title": "Requests Response Times (can filter by transction and url)",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 544 },
     "targets": [
      {
       "groupBy": [
        { "params": [ "name" ], "type": "tag" }
       ],
       "measurement": "/^$Measurement$/",
       "query": "SELECT count(\"value\") as \"Count\", min(\"value\") as \"Min\", mean(\"value\") as \"Avg\", max(\"value\") as \"Max\", percentile(\"value\", 95) as \"p95\" FROM http_req_duration WHERE $timeFilter AND (\"group\"::tag =~ /^$Transaction$/) AND (\"name\" =~ /^$URL$/) GROUP BY \"group\", \"name\"",
       "select": [
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "count"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "min"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "median"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "max"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ],
        [
         { "params": [ "value" ], "type": "field" },
         {
          "params": [
           95
          ],
          "type": "percentile"
         }
        ]
       ]
      }
     ]
    }
   ]
  },
  {
   "title": "Errors and Checks (can filter by transaction and url)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 45 }
  },
  {
   "title": "HTTP Request Errors (can filter by transaction and url)",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 46 },
   "targets": [
    {
     "query": "//SELECT \"group\", \"method\", \"name\", \"status\", \"error_code\", \"value\" FROM \"http_req_failed\" WHERE $timeFilter AND error_code != '' AND \"group\" =~ /^$Transaction$/ AND \"name\" =~ /^$URL$/ \r\n\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"http_req_failed\" and\r\n    r._field == \"value\" and\r\n    r.error_code != \"\"\r\n  )\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> filter(fn: (r) => contains(value: r.name, set: ${URL:json}))\r\n  |> keep(columns: [\"group\", \"method\", \"name\", \"status\", \"error_code\", \"_time\", \"_value\"])\r\n  |> group()"
    }
   ]
  },
  {
   "title": "Failed Checks (can filter by transaction)",
   "type": "table",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "query": "//SELECT \"value\" FROM \"checks\" WHERE $timeFilter AND \"group\" =~ /^$Transaction$/ AND \"value\" = 0 GROUP BY \"check\", \"group\"\r\n\r\nfrom(bucket: v.bucket)\r\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\r\n  |> filter(fn: (r) =>\r\n    r._measurement == \"checks\" and\r\n    r._field == \"value\" and\r\n    r._value == 0\r\n  )\r\n  |> filter(fn: (r) => contains(value: r.group, set: ${Transaction:json}))\r\n  |> keep(columns: [\"_time\", \"group\"])\r\n  |> group()"
    }
   ]
  }
 ]
}